language: python

matrix:
  include:
  - python: '2.7'
  - python: '3.4'
  - python: '3.5'
  - python: '3.6'
  - python: '3.7-dev'
  allow_failures:
  - python: '3.7-dev'

before_install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements-dev.txt
  # only Tested with this streamlink dev version
  - pip install -U git+https://github.com/back-to/streamlink.git@liveproxy

# install:
#  - pip install -e .

script:
  - pytest --cov=plugins
  - flake8 plugins/
